name: Update Metals & News (Free)

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install yfinance feedparser

      - name: Fetch metals data
        run: |
          python - <<'PY'
          import yfinance as yf, json
          metals = {}
          gold = yf.Ticker("GC=F").history(period="5d")['Close'].tolist()
          silver = yf.Ticker("SI=F").history(period="5d")['Close'].tolist()
          rates = {
              "USD": 1.0,
              "INR": 1 / yf.Ticker("INR=X").history(period="1d")['Close'].iloc[-1],
              "EUR": 1 / yf.Ticker("EURUSD=X").history(period="1d")['Close'].iloc[-1],
              "GBP": 1 / yf.Ticker("GBPUSD=X").history(period="1d")['Close'].iloc[-1],
              "JPY": 1 / yf.Ticker("JPY=X").history(period="1d")['Close'].iloc[-1],
          }
          metals["gold"] = gold
          metals["silver"] = silver
          metals["rates"] = rates
          with open("data/metals.json", "w") as f:
              json.dump(metals, f)
          PY

      - name: Fetch news (Google News RSS)
        run: |
          pip install feedparser
          python - <<'PY'
          import feedparser, json
          url = "https://news.google.com/rss/search?q=gold+OR+silver"
          feed = feedparser.parse(url)
          headlines = [entry.title for entry in feed.entries[:10]]
          with open("data/news.json", "w") as f:
              json.dump(headlines, f)
          PY

      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/metals.json data/news.json
          git commit -m "Update data [ci skip]" || echo "No changes"
          git push origin HEAD:main || true
